
files = [
    'src/event.cpp',
    'src/cli_mqtt.cpp',
    'src/cli_cmd.cpp',
    'src/cli.cpp',
    'src/json.cpp',
#    'src/cdplayer.cpp',
    'src/moon_clock.cpp',
    'src/moon_dates.c',
#    'src/gps.cpp',
    'src/xform.cpp',
    'src/json_dev.cpp',
    'src/builder.cpp',
    'src/builders.cpp',
    'src/http.cpp',
    'src/tick_actuator.cpp',
    'src/mains_monitor.cpp',
    'src/fmt.cpp',
    'src/date.cpp',

#    'test/main.cpp',
#    'test/cli.cpp',
#    'test/mqtt.cpp',
#    'test/moon_clock.cpp',
#    'test/xform.cpp',
#    'test/event.cpp',
#    'test/json.cpp',
#    'test/http.cpp',
#    'test/actuator.cpp',
#    'test/storage.cpp',
#    'test/fmt.cpp',
#    'test/date.cpp',

    'lib/cli/src/cli.c',
    'lib/cli/src/list.cpp',

    # https://github.com/eyalroz/printf
    'lib/printf/src/printf/printf.c',

]

panglos = [
    'src/thread.cpp',
    'src/time.cpp',
    'src/io.cpp',
    'src/object.cpp',
    'src/list.cpp',
    'src/json.cpp',
#    'src/device.cpp',
    'src/event_queue.cpp',
    'src/verbose.cpp',
    'src/socket.cpp',
    'src/batch.cpp',
    'src/network.cpp',

    'src/drivers/keyboard.cpp',
    'src/drivers/mcp23s17.cpp',
    'src/drivers/spi.cpp',
    'src/drivers/nmea.cpp',
    'src/drivers/mcp6s91.cpp',
    #'src/drivers/mcp3002.cpp',
    'src/drivers/7-segment.cpp',
    'src/drivers/ds3231.cpp',

    'src/linux/thread.cpp',
    'src/linux/mutex.cpp',
    'src/linux/queue.cpp',
    'src/linux/semaphore.cpp',
    'src/linux/time.cpp',

    #'unit-tests/stubs.cpp',
    'unit-tests/thread.cpp',

]

for path in panglos:
    files.append('../panglos/' + path)

ccflags = [
    '-Wswitch-default',
    #'-Wswitch-enum',
    '-Wconversion',
    #'-Wsign-conversion',
    '-Wunused-parameter',

    '-Wno-missing-field-initializers',
    '-Wno-format-zero-length',
    '-Wformat-security',

    '-g',
    '-DGTEST=1',
    '-DARCH_LINUX=1',
]

cpppath = [
    'src',
    'lib',
    'lib/printf/src',
    'lib/panglos/src',
    'lib/cli/src',
]

cflags = [
    '-Wall',
    '-Wextra',
    '-Werror',
]

cxxflags = [
    '-std=c++11',
    '-Wall',
    '-Wextra',
    '-Werror',
]

lflags = [
    '-lgtest_main',
    '-lgtest',
    '-lpthread',
    '-g',
]

libpath = [ ]

libs = []

import os
cc = os.environ.get('CC', 'gcc')
cxx = os.environ.get('CXX', 'g++')

if cc == 'clang':
    sane = [
        '-fsanitize=thread',
        '-fsanitize=alignment',
        '-fno-sanitize-recover=all',
        '-Wno-implicit-int-float-conversion',
    ]
    for x in sane:
        cflags  += [ x ]
        ccflags += [ x ]
        lflags  += [ x ]

env = Environment(CFLAGS=cflags, CCFLAGS=ccflags, CXXFLAGS=cxxflags, LINKFLAGS=lflags, CPPPATH=cpppath, CC=cc, CXX=cxx)
tdd = env.Program(target='tdd', source=files, LIBS=libs, LIBPATH=libpath)

